# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb711a4e5222652fb4b2bb9d4798b1169a2dc25393c22357db9de1abac6a15485634205042b9353417dceed0fd1355b9618d7ac0b34e14935b4f1fb798082f9e

test:
  secret_key_base: 4bc7521c805b56ff2708378cc0e2721f7697bd39499db079ea387d22f70d821f4dbcd2b7e0e478e4097973efafc0988538599d002225598d10b0d3386cace2e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
